<?php 
/**
 * Do NOT edit this file unless you know exactly what you are doing. This file is used to list your comments.
 *
 * @package Podcaster
 * @since 1.0
 */

	function mytheme_comment($comment, $args, $depth) {
		$GLOBALS['comment'] = $comment;
		extract($args, EXTR_SKIP);

		$pod_avtr_cmmts = pod_theme_option( 'pod-avatar-comments', true );

		if ( 'div' == $args['style'] ) {
			$tag = 'div';
			$add_below = 'comment';
		} else {
			$tag = 'li';
			$add_below = 'div-comment';
		}
	?>
			
	<<?php echo tag_escape( $tag ) ?> <?php comment_class(empty( $args['has_children'] ) ? '' : 'parent') ?> id="comment-<?php comment_ID() ?>">
	<?php if ( 'div' != $args['style'] ) : ?>
		<div id="div-comment-<?php comment_ID() ?>" class="comment-body">
	<?php endif; ?>
	<div class="comment-author vcard">
		<?php if ($pod_avtr_cmmts == true && $args['avatar_size'] != 0) echo get_avatar( $comment, $args['avatar_size'] ); ?>
		<?php printf(__('<span class="fn">%s</span>', 'podcaster'), get_comment_author_link()) ?>
		<span class="date">
			<a href="<?php echo htmlspecialchars( get_comment_link( $comment->comment_ID ) ) ?>"><?php printf( __('%1$s',  'podcaster' ), get_comment_date('M j, Y')) ?></a>
		</span>
	</div>
	<?php if ($comment->comment_approved == '0') : ?>
		<span class="comment-awaiting-moderation"><?php _e('Your comment is awaiting moderation.',  'podcaster' ) ?></span>
	<?php endif; ?>

	<div class="comment-text">
		<?php comment_text() ?>
	</div>
	<div class="reply">
		<?php comment_reply_link(array_merge( $args, array('add_below' => $add_below, 'depth' => $depth, 'max_depth' => $args['max_depth']))) ?>
	</div>
	<?php if ( 'div' != $args['style'] ) : ?>
		</div>
	<?php endif; ?>
 	<?php } ?>